import "./globals.css";

// ทำการตั้งค่าเมตาดาต้า
export const metadata = {
  title: "YWC20 Homework",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
